name: binary-rainfall-time-series-ml
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - seaborn
  - scikit-learn
  - xgboost
  - jupyterlab
  - jupyterlab_widgets
  - ipywidgets
  - statsmodels
  - kaggle
  - plotly
  - nodejs
  - pyarrow